### PR TITLE
feat: add authentication system

### PR DESCRIPTION
**Pull request by riflowth**
## Changes
- add cookie management
- add database connector (#3)
- add auth service with unit testing
- add login page in frontend
- add all needed repositories
- add authentication decorator

### CODE REVIEW

**Comment by eltfshr** [comment]
LGTM 👍 +4

**Review by eltfshr — COMMENTED** [review]
LGTM ❤️‍🔥

**Comment by riflowth** [comment]
Ok, It's ready to merge!!

**Comment by riflowth** [comment]
> LGTM ❤️‍🔥

Ok, I will merge it 🚀

**Pull request merged**
